// Autogenerated AST node on 08/11/2020, 15:59:03
package org.jpp.astnodes.ast;

public enum cmpopType {
    UNDEFINED,
    Eq,
    NotEq,
    Lt,
    LtE,
    Gt,
    GtE,
    Is,
    IsNot,
    In,
    NotIn;
}
