// Autogenerated AST node on 08/11/2020, 15:59:03
package org.jpp.astnodes.ast;

public enum operatorType {
    UNDEFINED,
    Add,
    Sub,
    Mult,
    MatMult,
    Div,
    Mod,
    Pow,
    LShift,
    RShift,
    BitOr,
    BitXor,
    BitAnd,
    FloorDiv;
}
