// Autogenerated AST node on 08/11/2020, 15:59:03
package org.jpp.astnodes.base;
import org.antlr.runtime.Token;
import org.jpp.astnodes.AST;
import org.jpp.astnodes.PythonTree;
import org.jpp.heart.PyUnicode;
import org.jpp.heart.PyType;
import org.jpp.exposers.ExposedGet;
import org.jpp.exposers.ExposedType;

@ExposedType(name = "_ast.excepthandler", base = AST.class)
public abstract class excepthandler extends PythonTree {

    public static final PyType TYPE = PyType.fromClass(excepthandler.class);
    private final static PyUnicode[] fields = new PyUnicode[0];
    @ExposedGet(name = "_fields")
    public PyUnicode[] get_fields() { return fields; }

    private final static PyUnicode[] attributes =
    new PyUnicode[] {new PyUnicode("lineno"), new PyUnicode("col_offset")};
    @ExposedGet(name = "_attributes")
    public PyUnicode[] get_attributes() { return attributes; }

    public excepthandler() {
    }

    public excepthandler(PyType subType) {
    }

    public excepthandler(int ttype, Token token) {
        super(ttype, token);
    }

    public excepthandler(Token token) {
        super(token);
    }

    public excepthandler(PythonTree node) {
        super(node);
    }

}
