/*******************************************************************************
 * Copyright (c) 2000, 2019 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
	// BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 143,
					MAX_NAME_LENGTH = 53,
					NUM_STATES = 1338,

					NT_OFFSET = 143,
					SCOPE_UBOUND = 337,
					SCOPE_SIZE = 338,
					LA_STATE_OFFSET = 19575,
					MAX_LA = 1,
					NUM_RULES = 960,
					NUM_TERMINALS = 143,
					NUM_NON_TERMINALS = 438,
					NUM_SYMBOLS = 581,
					START_STATE = 1860,
					EOFT_SYMBOL = 90,
					EOLT_SYMBOL = 90,
					ACCEPT_ACTION = 19574,
					ERROR_ACTION = 19575;
}
