/*******************************************************************************
 * Copyright (c) 2000, 2019 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
	// BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 137,
					MAX_NAME_LENGTH = 53,
					NUM_STATES = 1239,

					NT_OFFSET = 137,
					SCOPE_UBOUND = 315,
					SCOPE_SIZE = 316,
					LA_STATE_OFFSET = 18462,
					MAX_LA = 1,
					NUM_RULES = 930,
					NUM_TERMINALS = 137,
					NUM_NON_TERMINALS = 429,
					NUM_SYMBOLS = 566,
					START_STATE = 1132,
					EOFT_SYMBOL = 65,
					EOLT_SYMBOL = 65,
					ACCEPT_ACTION = 18461,
					ERROR_ACTION = 18462;
}
