/*******************************************************************************
 * Copyright (c) 2000, 2019 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
	// BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 138,
					MAX_NAME_LENGTH = 53,
					NUM_STATES = 1282,

					NT_OFFSET = 138,
					SCOPE_UBOUND = 318,
					SCOPE_SIZE = 319,
					LA_STATE_OFFSET = 18963,
					MAX_LA = 1,
					NUM_RULES = 937,
					NUM_TERMINALS = 138,
					NUM_NON_TERMINALS = 431,
					NUM_SYMBOLS = 569,
					START_STATE = 1146,
					EOFT_SYMBOL = 67,
					EOLT_SYMBOL = 67,
					ACCEPT_ACTION = 18962,
					ERROR_ACTION = 18963;
}
