/*******************************************************************************
 * Copyright (c) 2000, 2019 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameNotAToken = 0,
							TokenNameWHITESPACE = 1000,
							TokenNameCOMMENT_LINE = 1001,
							TokenNameCOMMENT_BLOCK = 1002,
							TokenNameCOMMENT_JAVADOC = 1003;

	// BEGIN_AUTOGENERATED_REGION
	int TokenNameIdentifier = 25,
							TokenNameabstract = 57,
							TokenNameassert = 97,
							TokenNameboolean = 111,
							TokenNamebreak = 98,
							TokenNamebyte = 112,
							TokenNamecase = 108,
							TokenNamecatch = 113,
							TokenNamechar = 114,
							TokenNameclass = 86,
							TokenNamecontinue = 99,
							TokenNameconst = 140,
							TokenNamedefault = 92,
							TokenNamedo = 100,
							TokenNamedouble = 115,
							TokenNameelse = 73,
							TokenNameenum = 88,
							TokenNameextends = 109,
							TokenNamefalse = 43,
							TokenNamefinal = 58,
							TokenNamefinally = 122,
							TokenNamefloat = 116,
							TokenNamefor = 40,
							TokenNamegoto = 141,
							TokenNameif = 93,
							TokenNameimplements = 135,
							TokenNameimport = 117,
							TokenNameinstanceof = 17,
							TokenNameint = 118,
							TokenNameinterface = 87,
							TokenNamelong = 119,
							TokenNamenative = 59,
							TokenNamenew = 37,
							TokenNamenon_sealed = 60,
							TokenNamenull = 44,
							TokenNamepackage = 107,
							TokenNameprivate = 61,
							TokenNameprotected = 62,
							TokenNamepublic = 63,
							TokenNamereturn = 101,
							TokenNameshort = 120,
							TokenNamestatic = 41,
							TokenNamestrictfp = 64,
							TokenNamesuper = 35,
							TokenNameswitch = 67,
							TokenNamesynchronized = 54,
							TokenNamethis = 36,
							TokenNamethrow = 94,
							TokenNamethrows = 123,
							TokenNametransient = 65,
							TokenNametrue = 45,
							TokenNametry = 102,
							TokenNamevoid = 121,
							TokenNamevolatile = 66,
							TokenNamewhile = 95,
							TokenNamemodule = 125,
							TokenNameopen = 126,
							TokenNamerequires = 127,
							TokenNametransitive = 133,
							TokenNameexports = 128,
							TokenNameopens = 129,
							TokenNameto = 136,
							TokenNameuses = 130,
							TokenNameprovides = 131,
							TokenNamewith = 137,
							TokenNamewithstmt = 103,
							TokenNamein = 21,
							TokenNamepyjavatuple = 23,
							TokenNamenot = 22,
							TokenNameyieldr = 104,
							TokenNameIntegerLiteral = 46,
							TokenNameLongLiteral = 47,
							TokenNameFloatingPointLiteral = 48,
							TokenNameDoubleLiteral = 49,
							TokenNameCharacterLiteral = 50,
							TokenNameStringLiteral = 51,
							TokenNameTextBlock = 52,
							TokenNamePLUS_PLUS = 1,
							TokenNameMINUS_MINUS = 2,
							TokenNameEQUAL_EQUAL = 19,
							TokenNameLESS_EQUAL = 12,
							TokenNameGREATER_EQUAL = 13,
							TokenNameNOT_EQUAL = 20,
							TokenNameLEFT_SHIFT = 18,
							TokenNameRIGHT_SHIFT = 14,
							TokenNameUNSIGNED_RIGHT_SHIFT = 16,
							TokenNamePLUS_EQUAL = 74,
							TokenNameMINUS_EQUAL = 75,
							TokenNameMULTIPLY_EQUAL = 76,
							TokenNamePOWER_EQUAL = 77,
							TokenNameDIVIDE_EQUAL = 78,
							TokenNameAND_EQUAL = 79,
							TokenNameOR_EQUAL = 80,
							TokenNameXOR_EQUAL = 81,
							TokenNameREMAINDER_EQUAL = 82,
							TokenNameLEFT_SHIFT_EQUAL = 83,
							TokenNameRIGHT_SHIFT_EQUAL = 84,
							TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 85,
							TokenNameOR_OR = 32,
							TokenNameAND_AND = 30,
							TokenNamePLUS = 3,
							TokenNameMINUS = 4,
							TokenNameNOT = 69,
							TokenNameREMAINDER = 7,
							TokenNameXOR = 26,
							TokenNameAND = 24,
							TokenNameMULTIPLY = 6,
							TokenNamePOWER = 142,
							TokenNameOR = 28,
							TokenNameTWIDDLE = 70,
							TokenNameDIVIDE = 8,
							TokenNameGREATER = 15,
							TokenNameLESS = 9,
							TokenNameLPAREN = 27,
							TokenNameRPAREN = 33,
							TokenNameLBRACE = 42,
							TokenNameRBRACE = 55,
							TokenNameLBRACKET = 11,
							TokenNameRBRACKET = 106,
							TokenNameSEMICOLON = 34,
							TokenNameQUESTION = 31,
							TokenNameCOLON = 91,
							TokenNameCOMMA = 38,
							TokenNameDOT = 5,
							TokenNameEQUAL = 72,
							TokenNameAT = 39,
							TokenNameELLIPSIS = 124,
							TokenNameARROW = 110,
							TokenNameCOLON_COLON = 10,
							TokenNameCOLON_COLON_COLON = 68,
							TokenNameBeginLambda = 53,
							TokenNameBeginIntersectionCast = 71,
							TokenNameBeginTypeArguments = 105,
							TokenNameElidedSemicolonAndRightBrace = 138,
							TokenNameAT308 = 29,
							TokenNameAT308DOTDOTDOT = 134,
							TokenNameBeginCaseExpr = 139,
							TokenNameRestrictedIdentifierYield = 96,
							TokenNameRestrictedIdentifierrecord = 89,
							TokenNameRestrictedIdentifiersealed = 56,
							TokenNameRestrictedIdentifierpermits = 132,
							TokenNameEOF = 90,
							TokenNameERROR = 143;
}
