/*******************************************************************************
 * Copyright (c) 2000, 2019 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameNotAToken = 0,
							TokenNameWHITESPACE = 1000,
							TokenNameCOMMENT_LINE = 1001,
							TokenNameCOMMENT_BLOCK = 1002,
							TokenNameCOMMENT_JAVADOC = 1003;

	// BEGIN_AUTOGENERATED_REGION
	int TokenNameIdentifier = 25,
							TokenNameassert = 93,
							TokenNameboolean = 108,
							TokenNamebreak = 94,
							TokenNamecase = 105,
							TokenNamecatch = 109,
							TokenNamechar = 110,
							TokenNameclass = 70,
							TokenNamecontinue = 95,
							TokenNamedefault = 88,
							TokenNamedo = 96,
							TokenNamedouble = 111,
							TokenNameelse = 69,
							TokenNameenum = 85,
							TokenNameextends = 106,
							TokenNamefalse = 46,
							TokenNamefinal = 47,
							TokenNamefinally = 117,
							TokenNamefloat = 112,
							TokenNamefor = 43,
							TokenNamegoto = 135,
							TokenNameif = 89,
							TokenNameimplements = 130,
							TokenNameimport = 113,
							TokenNameinstanceof = 17,
							TokenNameint = 114,
							TokenNameinterface = 84,
							TokenNamelong = 115,
							TokenNamenew = 38,
							TokenNamenon_sealed = 48,
							TokenNamenull = 49,
							TokenNamepackage = 104,
							TokenNameprivate = 50,
							TokenNamepublic = 51,
							TokenNamereturn = 97,
							TokenNamestatic = 40,
							TokenNamestrictfp = 52,
							TokenNamesuper = 35,
							TokenNameswitch = 63,
							TokenNamesynchronized = 41,
							TokenNamethis = 36,
							TokenNamethrow = 90,
							TokenNamethrows = 118,
							TokenNametransient = 53,
							TokenNametrue = 54,
							TokenNametry = 98,
							TokenNamevoid = 116,
							TokenNamewhile = 91,
							TokenNamemodule = 120,
							TokenNameopen = 121,
							TokenNamerequires = 122,
							TokenNametransitive = 128,
							TokenNameexports = 123,
							TokenNameopens = 124,
							TokenNameto = 131,
							TokenNameuses = 125,
							TokenNameprovides = 126,
							TokenNamewith = 132,
							TokenNamewithstmt = 99,
							TokenNamein = 21,
							TokenNamepyjavatuple = 23,
							TokenNamenot = 22,
							TokenNameyieldr = 100,
							TokenNamenonlocal = 101,
							TokenNameIntegerLiteral = 55,
							TokenNameLongLiteral = 56,
							TokenNameFloatingPointLiteral = 57,
							TokenNameDoubleLiteral = 58,
							TokenNameCharacterLiteral = 59,
							TokenNameStringLiteral = 60,
							TokenNameTextBlock = 61,
							TokenNamePLUS_PLUS = 1,
							TokenNameMINUS_MINUS = 2,
							TokenNameEQUAL_EQUAL = 19,
							TokenNameLESS_EQUAL = 12,
							TokenNameGREATER_EQUAL = 13,
							TokenNameNOT_EQUAL = 20,
							TokenNameLEFT_SHIFT = 18,
							TokenNameRIGHT_SHIFT = 14,
							TokenNameUNSIGNED_RIGHT_SHIFT = 16,
							TokenNamePLUS_EQUAL = 71,
							TokenNameMINUS_EQUAL = 72,
							TokenNameMULTIPLY_EQUAL = 73,
							TokenNamePOWER_EQUAL = 74,
							TokenNameDIVIDE_EQUAL = 75,
							TokenNameAND_EQUAL = 76,
							TokenNameOR_EQUAL = 77,
							TokenNameXOR_EQUAL = 78,
							TokenNameREMAINDER_EQUAL = 79,
							TokenNameLEFT_SHIFT_EQUAL = 80,
							TokenNameRIGHT_SHIFT_EQUAL = 81,
							TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 82,
							TokenNameOR_OR = 32,
							TokenNameAND_AND = 30,
							TokenNamePLUS = 3,
							TokenNameMINUS = 4,
							TokenNameNOT = 65,
							TokenNameREMAINDER = 7,
							TokenNameXOR = 26,
							TokenNameAND = 24,
							TokenNameMULTIPLY = 6,
							TokenNamePOWER = 136,
							TokenNameOR = 28,
							TokenNameTWIDDLE = 66,
							TokenNameDIVIDE = 8,
							TokenNameGREATER = 15,
							TokenNameLESS = 9,
							TokenNameLPAREN = 27,
							TokenNameRPAREN = 34,
							TokenNameLBRACE = 44,
							TokenNameRBRACE = 42,
							TokenNameLBRACKET = 11,
							TokenNameRBRACKET = 103,
							TokenNameSEMICOLON = 33,
							TokenNameQUESTION = 31,
							TokenNameCOLON = 87,
							TokenNameCOMMA = 37,
							TokenNameDOT = 5,
							TokenNameEQUAL = 68,
							TokenNameAT = 39,
							TokenNameELLIPSIS = 119,
							TokenNameARROW = 107,
							TokenNameCOLON_COLON = 10,
							TokenNameCOLON_COLON_COLON = 64,
							TokenNameBeginLambda = 62,
							TokenNameBeginIntersectionCast = 67,
							TokenNameBeginTypeArguments = 102,
							TokenNameElidedSemicolonAndRightBrace = 133,
							TokenNameAT308 = 29,
							TokenNameAT308DOTDOTDOT = 129,
							TokenNameBeginCaseExpr = 134,
							TokenNameRestrictedIdentifierYield = 92,
							TokenNameRestrictedIdentifierrecord = 86,
							TokenNameRestrictedIdentifiersealed = 45,
							TokenNameRestrictedIdentifierpermits = 127,
							TokenNameEOF = 83,
							TokenNameERROR = 137;
}
